<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Shared\"/>
        <Folder Include="Specifications\"/>
        <Folder Include="ValueObjects\"/>
        <InternalsVisibleTo Include="FitTracker.Infrastructure"/>
        <InternalsVisibleTo Include="FitTrackerInfrastructure.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
