<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Exceptions\" />
		<Folder Include="Shared\" />
		<Folder Include="Specifications\" />
		<InternalsVisibleTo Include="FitTracker.Infrastructure" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
