// <auto-generated />
using System;
using FitTracker.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitTracker.Infrastructure.Migrations
{
    [DbContext(typeof(FitTrackerDbContext))]
    [Migration("20251109123815_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.AchievementEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlocked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsUnlocked")
                        .HasDatabaseName("IX_Achievements_IsUnlocked");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Achievements_UserId");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("IX_Achievements_User_Type");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("Equipment")
                        .HasColumnType("integer")
                        .HasColumnName("equipment");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_custom");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("Equipment")
                        .HasDatabaseName("IX_Exercises_Equipment");

                    b.HasIndex("MuscleGroup")
                        .HasDatabaseName("IX_Exercises_MuscleGroup");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Exercises_Name");

                    b.HasIndex("UserId", "IsCustom")
                        .HasDatabaseName("IX_Exercises_User_Custom");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseRecordEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<DateTime>("LastPerformed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_performed");

                    b.Property<int>("MaxReps")
                        .HasColumnType("integer")
                        .HasColumnName("max_reps");

                    b.Property<DateTime>("MaxRepsDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_reps_date");

                    b.Property<decimal>("MaxTotalVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("max_total_volume");

                    b.Property<DateTime>("MaxTotalVolumeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_total_volume_date");

                    b.Property<decimal>("MaxVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("max_volume");

                    b.Property<DateTime>("MaxVolumeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_volume_date");

                    b.Property<DateTime>("MaxWeightDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_weight_date");

                    b.Property<decimal>("MaxWeight_Kilograms")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_weight_kg");

                    b.Property<decimal>("TotalLifted")
                        .HasColumnType("numeric")
                        .HasColumnName("total_lifted");

                    b.Property<int>("TotalReps")
                        .HasColumnType("integer")
                        .HasColumnName("total_reps");

                    b.Property<int>("TotalSets")
                        .HasColumnType("integer")
                        .HasColumnName("total_sets");

                    b.Property<int>("TotalWorkouts")
                        .HasColumnType("integer")
                        .HasColumnName("total_workouts");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LastPerformed")
                        .HasDatabaseName("IX_ExerciseRecords_LastPerformed");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique()
                        .HasDatabaseName("IX_ExerciseRecords_User_Exercise");

                    b.ToTable("exercise_records", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.SetEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<int>("SetType")
                        .HasColumnType("integer")
                        .HasColumnName("set_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight_kg");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("IX_Sets_IsCompleted");

                    b.HasIndex("WorkoutExerciseId")
                        .HasDatabaseName("IX_Sets_WorkoutExerciseId");

                    b.HasIndex("WorkoutExerciseId", "SetNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Sets_WorkoutExercise_SetNumber");

                    b.ToTable("sets", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.TemplateSetEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int>("PlannedReps")
                        .HasColumnType("integer")
                        .HasColumnName("planned_reps");

                    b.Property<decimal>("PlannedWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("planned_weight");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<int>("SetType")
                        .HasColumnType("integer")
                        .HasColumnName("set_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("WorkoutTemplateExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateExerciseId")
                        .HasDatabaseName("IX_TemplateSets_TemplateExerciseId");

                    b.HasIndex("WorkoutTemplateExerciseId", "SetNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_TemplateSets_TemplateExercise_SetNumber");

                    b.ToTable("template_sets", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredUnits")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_units");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_progress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<decimal>("TotalVolumeKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_volume_kg");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("workout_date");

                    b.Property<Guid?>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("IX_Workouts_IsCompleted");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Workouts_UserId");

                    b.HasIndex("WorkoutDate")
                        .HasDatabaseName("IX_Workouts_WorkoutDate");

                    b.HasIndex("WorkoutTemplateId")
                        .HasDatabaseName("IX_Workouts_TemplateId");

                    b.HasIndex("UserId", "WorkoutDate")
                        .HasDatabaseName("IX_Workouts_User_Date");

                    b.ToTable("workouts", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutExerciseEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("IX_WorkoutExercises_ExerciseId");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("IX_WorkoutExercises_WorkoutId");

                    b.HasIndex("WorkoutId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkoutExercises_Workout_Order");

                    b.ToTable("workout_exercises", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_WorkoutTemplates_UserId");

                    b.HasIndex("UserId", "LastUsedAt")
                        .HasDatabaseName("IX_WorkoutTemplates_User_LastUsed");

                    b.ToTable("workout_templates", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateExerciseEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("IX_WorkoutTemplateExercises_ExerciseId");

                    b.HasIndex("WorkoutTemplateId")
                        .HasDatabaseName("IX_WorkoutTemplateExercises_TemplateId");

                    b.HasIndex("WorkoutTemplateId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkoutTemplateExercises_Template_Order");

                    b.ToTable("workout_template_exercises", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.AchievementEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "User")
                        .WithMany("CustomExercises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseRecordEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "User")
                        .WithMany("ExerciseRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.SetEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutExerciseEf", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.TemplateSetEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateExerciseEf", "WorkoutTemplateExercise")
                        .WithMany("PlannedSets")
                        .HasForeignKey("WorkoutTemplateExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplateExercise");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutExerciseEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutEf", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "User")
                        .WithMany("WorkoutTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateExerciseEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("CustomExercises");

                    b.Navigation("ExerciseRecords");

                    b.Navigation("WorkoutTemplates");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutEf", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutExerciseEf", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateExerciseEf", b =>
                {
                    b.Navigation("PlannedSets");
                });
#pragma warning restore 612, 618
        }
    }
}
