// <auto-generated />
using System;
using FitTracker.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitTracker.Infrastructure.Migrations
{
    [DbContext(typeof(FitTrackerDbContext))]
    [Migration("20260106160332_AddOutboxTable")]
    partial class AddOutboxTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.AchievementEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.ToTable("achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete your first workout",
                            IconUrl = "/icons/achievement_first.png",
                            Name = "First Steps",
                            Target = 1,
                            Tier = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 7 consecutive days of workouts",
                            IconUrl = "/icons/achievement_streak.png",
                            Name = "Consistency King",
                            Target = 7,
                            Tier = 1,
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete 100 total workouts",
                            IconUrl = "/icons/achievement_century.png",
                            Name = "Century Club",
                            Target = 100,
                            Tier = 2,
                            Type = 2,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lift a total of 50,000 kg",
                            IconUrl = "/icons/achievement_iron.png",
                            Name = "Iron Warrior",
                            Target = 50000,
                            Tier = 2,
                            Type = 3,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set 20 personal records",
                            IconUrl = "/icons/achievement_pr.png",
                            Name = "Record Breaker",
                            Target = 20,
                            Tier = 1,
                            Type = 4,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("Equipment")
                        .HasColumnType("integer")
                        .HasColumnName("equipment");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_exercises_standard")
                        .HasFilter("created_by_user_id IS NULL");

                    b.HasIndex("MuscleGroup")
                        .HasDatabaseName("IX_exercises_muscle_group");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_exercises_name");

                    b.ToTable("exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compound chest exercise performed on a flat bench",
                            Equipment = 1,
                            MuscleGroup = 0,
                            Name = "Barbell Bench Press",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fundamental lower body compound exercise",
                            Equipment = 1,
                            MuscleGroup = 3,
                            Name = "Barbell Back Squat",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full body compound pulling exercise",
                            Equipment = 1,
                            MuscleGroup = 1,
                            Name = "Conventional Deadlift",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standing barbell shoulder press",
                            Equipment = 1,
                            MuscleGroup = 2,
                            Name = "Overhead Press",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bodyweight vertical pulling exercise",
                            Equipment = 5,
                            MuscleGroup = 1,
                            Name = "Pull-Ups",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bent-over barbell rowing exercise",
                            Equipment = 1,
                            MuscleGroup = 1,
                            Name = "Barbell Row",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222227"),
                            CreatedAt = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Custom bicep curl variation",
                            Equipment = 2,
                            MuscleGroup = 4,
                            Name = "John's Special Curl",
                            UpdatedAt = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseRecordEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<DateTime>("LastPerformed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_performed");

                    b.Property<int>("MaxReps")
                        .HasColumnType("integer")
                        .HasColumnName("max_reps");

                    b.Property<DateTime>("MaxRepsDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_reps_date");

                    b.Property<DateTime>("MaxTotalVolumeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_total_volume_date");

                    b.Property<double>("MaxTotalVolumeKg")
                        .HasColumnType("double precision")
                        .HasColumnName("max_total_volume");

                    b.Property<DateTime>("MaxVolumeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_volume_date");

                    b.Property<double>("MaxVolumeKg")
                        .HasColumnType("double precision")
                        .HasColumnName("max_volume");

                    b.Property<DateTime>("MaxWeightDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_weight_date");

                    b.Property<double>("MaxWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("max_weight_kg");

                    b.Property<double>("TotalLiftedKg")
                        .HasColumnType("double precision")
                        .HasColumnName("total_lifted");

                    b.Property<int>("TotalReps")
                        .HasColumnType("integer")
                        .HasColumnName("total_reps");

                    b.Property<int>("TotalSets")
                        .HasColumnType("integer")
                        .HasColumnName("total_sets");

                    b.Property<int>("TotalWorkouts")
                        .HasColumnType("integer")
                        .HasColumnName("total_workouts");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LastPerformed")
                        .HasDatabaseName("IX_ExerciseRecords_LastPerformed");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique()
                        .HasDatabaseName("IX_ExerciseRecords_User_Exercise");

                    b.ToTable("exercise_records", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999991"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222221"),
                            LastPerformed = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxReps = 12,
                            MaxRepsDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTotalVolumeDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTotalVolumeKg = 4500.0,
                            MaxVolumeDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxVolumeKg = 960.0,
                            MaxWeightDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxWeightKg = 100.0,
                            TotalLiftedKg = 42000.0,
                            TotalReps = 576,
                            TotalSets = 72,
                            TotalWorkouts = 24,
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999992"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LastPerformed = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxReps = 10,
                            MaxRepsDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTotalVolumeDate = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTotalVolumeKg = 5200.0,
                            MaxVolumeDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxVolumeKg = 1200.0,
                            MaxWeightDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxWeightKg = 140.0,
                            TotalLiftedKg = 58000.0,
                            TotalReps = 504,
                            TotalSets = 63,
                            TotalWorkouts = 21,
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999993"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222223"),
                            LastPerformed = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxReps = 8,
                            MaxRepsDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTotalVolumeDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTotalVolumeKg = 4800.0,
                            MaxVolumeDate = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxVolumeKg = 1280.0,
                            MaxWeightDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxWeightKg = 180.0,
                            TotalLiftedKg = 48000.0,
                            TotalReps = 324,
                            TotalSets = 54,
                            TotalWorkouts = 18,
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999994"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222224"),
                            LastPerformed = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxReps = 10,
                            MaxRepsDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTotalVolumeDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTotalVolumeKg = 2100.0,
                            MaxVolumeDate = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxVolumeKg = 520.0,
                            MaxWeightDate = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxWeightKg = 65.0,
                            TotalLiftedKg = 28000.0,
                            TotalReps = 480,
                            TotalSets = 60,
                            TotalWorkouts = 20,
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_Unprocessed");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.SetEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<int>("SetType")
                        .HasColumnType("integer")
                        .HasColumnName("set_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<double>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("weight_kg");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("IX_Sets_IsCompleted");

                    b.HasIndex("WorkoutExerciseId")
                        .HasDatabaseName("IX_Sets_WorkoutExerciseId");

                    b.HasIndex("WorkoutExerciseId", "SetNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Sets_WorkoutExercise_SetNumber");

                    b.ToTable("sets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888801"),
                            CompletedAt = new DateTime(2024, 11, 8, 10, 5, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 8, 10, 3, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 10,
                            RestSeconds = 120,
                            SetNumber = 1,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 8, 10, 5, 0, 0, DateTimeKind.Utc),
                            WeightKg = 60.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777771")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888802"),
                            CompletedAt = new DateTime(2024, 11, 8, 10, 10, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 8, 10, 7, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 8,
                            RestSeconds = 120,
                            SetNumber = 2,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 8, 10, 10, 0, 0, DateTimeKind.Utc),
                            WeightKg = 70.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777771")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888803"),
                            CompletedAt = new DateTime(2024, 11, 8, 10, 15, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 8, 10, 12, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 6,
                            RestSeconds = 180,
                            SetNumber = 3,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 8, 10, 15, 0, 0, DateTimeKind.Utc),
                            WeightKg = 80.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777771")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888804"),
                            CompletedAt = new DateTime(2024, 11, 8, 10, 40, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 8, 10, 38, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 10,
                            RestSeconds = 90,
                            SetNumber = 1,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 8, 10, 40, 0, 0, DateTimeKind.Utc),
                            WeightKg = 40.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777772")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888805"),
                            CompletedAt = new DateTime(2024, 11, 8, 10, 45, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 8, 10, 42, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 8,
                            RestSeconds = 90,
                            SetNumber = 2,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 8, 10, 45, 0, 0, DateTimeKind.Utc),
                            WeightKg = 45.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777772")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888806"),
                            CompletedAt = new DateTime(2024, 11, 9, 10, 5, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 9, 10, 3, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 8,
                            RestSeconds = 120,
                            SetNumber = 1,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 9, 10, 5, 0, 0, DateTimeKind.Utc),
                            WeightKg = 10.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777773")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888807"),
                            CompletedAt = new DateTime(2024, 11, 9, 10, 10, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 9, 10, 7, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 7,
                            RestSeconds = 120,
                            SetNumber = 2,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 9, 10, 10, 0, 0, DateTimeKind.Utc),
                            WeightKg = 10.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777773")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888808"),
                            CompletedAt = new DateTime(2024, 11, 9, 10, 35, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 9, 10, 33, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 8,
                            RestSeconds = 90,
                            SetNumber = 1,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 9, 10, 35, 0, 0, DateTimeKind.Utc),
                            WeightKg = 80.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777774")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888809"),
                            CompletedAt = new DateTime(2024, 11, 9, 10, 40, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 9, 10, 37, 0, 0, DateTimeKind.Utc),
                            IsCompleted = true,
                            Reps = 6,
                            RestSeconds = 90,
                            SetNumber = 2,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 11, 9, 10, 40, 0, 0, DateTimeKind.Utc),
                            WeightKg = 85.0,
                            WorkoutExerciseId = new Guid("77777777-7777-7777-7777-777777777774")
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.TemplateSetEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int>("PlannedReps")
                        .HasColumnType("integer")
                        .HasColumnName("planned_reps");

                    b.Property<double>("PlannedWeightKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("planned_weight");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<int>("SetType")
                        .HasColumnType("integer")
                        .HasColumnName("set_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("WorkoutTemplateExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateExerciseId")
                        .HasDatabaseName("IX_TemplateSets_TemplateExerciseId");

                    b.HasIndex("WorkoutTemplateExerciseId", "SetNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_TemplateSets_TemplateExercise_SetNumber");

                    b.ToTable("template_sets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666601"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlannedReps = 10,
                            PlannedWeightKg = 60.0,
                            RestSeconds = 120,
                            SetNumber = 1,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateExerciseId = new Guid("55555555-5555-5555-5555-555555555551")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666602"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlannedReps = 8,
                            PlannedWeightKg = 70.0,
                            RestSeconds = 120,
                            SetNumber = 2,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateExerciseId = new Guid("55555555-5555-5555-5555-555555555551")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666603"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlannedReps = 5,
                            PlannedWeightKg = 80.0,
                            RestSeconds = 180,
                            SetNumber = 3,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateExerciseId = new Guid("55555555-5555-5555-5555-555555555551")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666604"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlannedReps = 10,
                            PlannedWeightKg = 40.0,
                            RestSeconds = 90,
                            SetNumber = 1,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateExerciseId = new Guid("55555555-5555-5555-5555-555555555552")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666605"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlannedReps = 8,
                            PlannedWeightKg = 45.0,
                            RestSeconds = 90,
                            SetNumber = 2,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateExerciseId = new Guid("55555555-5555-5555-5555-555555555552")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666606"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlannedReps = 6,
                            PlannedWeightKg = 50.0,
                            RestSeconds = 120,
                            SetNumber = 3,
                            SetType = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateExerciseId = new Guid("55555555-5555-5555-5555-555555555552")
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.UserAchievementEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUnlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unlocked");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId")
                        .HasDatabaseName("IX_user_achievements_achievement_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_achievements_user_id");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_achievements_user_id_achievement_id");

                    b.ToTable("user_achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AchievementId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsUnlocked = true,
                            Progress = 1,
                            UnlockedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            AchievementId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsUnlocked = true,
                            Progress = 7,
                            UnlockedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            AchievementId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsUnlocked = false,
                            Progress = 63,
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            AchievementId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsUnlocked = true,
                            Progress = 50000,
                            UnlockedAt = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            AchievementId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsUnlocked = false,
                            Progress = 12,
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("GoogleProviderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_provider_id");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Avatar = "https://example.com/avatars/john.jpg",
                            Bio = "Passionate about fitness and strength training. 5 years experience.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fitnesspro@example.com",
                            FirstName = "John",
                            IsEmailVerified = true,
                            LastName = "Athlete",
                            PasswordHash = "$2a$11$20pVjNtw/EknLSvVjig.z.7aFDUPZhUajZoFvr2lncrVgR2/kNJMW",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "fitness_pro"
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_progress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<double>("TotalVolumeKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("total_volume_kg");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("workout_date");

                    b.Property<Guid?>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("IX_Workouts_IsCompleted");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Workouts_UserId");

                    b.HasIndex("WorkoutDate")
                        .HasDatabaseName("IX_Workouts_WorkoutDate");

                    b.HasIndex("WorkoutTemplateId")
                        .HasDatabaseName("IX_Workouts_TemplateId");

                    b.HasIndex("UserId", "WorkoutDate")
                        .HasDatabaseName("IX_Workouts_User_Date");

                    b.ToTable("workouts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            CompletedAt = new DateTime(2024, 11, 8, 11, 15, 30, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Duration = new TimeSpan(0, 1, 15, 30, 0),
                            IsCompleted = true,
                            IsInProgress = false,
                            Name = "Push Day - Nov 8",
                            Notes = "Great workout, felt strong",
                            StartedAt = new DateTime(2024, 11, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            TotalVolumeKg = 1450.5,
                            UpdatedAt = new DateTime(2024, 11, 8, 11, 15, 30, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WorkoutDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            CompletedAt = new DateTime(2024, 11, 9, 11, 5, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 11, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Duration = new TimeSpan(0, 1, 5, 0, 0),
                            IsCompleted = true,
                            IsInProgress = false,
                            Name = "Pull Day - Nov 9",
                            StartedAt = new DateTime(2024, 11, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            TotalVolumeKg = 1280.0,
                            UpdatedAt = new DateTime(2024, 11, 9, 11, 5, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WorkoutDate = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateId = new Guid("33333333-3333-3333-3333-333333333332")
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutExerciseEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("IX_WorkoutExercises_ExerciseId");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("IX_WorkoutExercises_WorkoutId");

                    b.HasIndex("WorkoutId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkoutExercises_Workout_Order");

                    b.ToTable("workout_exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAt = new DateTime(2024, 11, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Notes = "Good form today",
                            OrderIndex = 1,
                            UpdatedAt = new DateTime(2024, 11, 8, 10, 30, 0, 0, DateTimeKind.Utc),
                            WorkoutId = new Guid("44444444-4444-4444-4444-444444444441")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            CreatedAt = new DateTime(2024, 11, 8, 10, 35, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222224"),
                            OrderIndex = 2,
                            UpdatedAt = new DateTime(2024, 11, 8, 11, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutId = new Guid("44444444-4444-4444-4444-444444444441")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777773"),
                            CreatedAt = new DateTime(2024, 11, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222225"),
                            Notes = "Added 10kg weight",
                            OrderIndex = 1,
                            UpdatedAt = new DateTime(2024, 11, 9, 10, 25, 0, 0, DateTimeKind.Utc),
                            WorkoutId = new Guid("44444444-4444-4444-4444-444444444442")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777774"),
                            CreatedAt = new DateTime(2024, 11, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222226"),
                            OrderIndex = 2,
                            UpdatedAt = new DateTime(2024, 11, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutId = new Guid("44444444-4444-4444-4444-444444444442")
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_WorkoutTemplates_UserId");

                    b.HasIndex("UserId", "LastUsedAt")
                        .HasDatabaseName("IX_WorkoutTemplates_User_LastUsed");

                    b.ToTable("workout_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chest, shoulders, and triceps workout",
                            LastUsedAt = new DateTime(2024, 11, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Push Day",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageCount = 8,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Back and biceps workout",
                            LastUsedAt = new DateTime(2024, 11, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pull Day",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageCount = 8,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lower body workout",
                            LastUsedAt = new DateTime(2024, 11, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Leg Day",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageCount = 7,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateExerciseEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("IX_WorkoutTemplateExercises_ExerciseId");

                    b.HasIndex("WorkoutTemplateId")
                        .HasDatabaseName("IX_WorkoutTemplateExercises_TemplateId");

                    b.HasIndex("WorkoutTemplateId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkoutTemplateExercises_Template_Order");

                    b.ToTable("workout_template_exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Notes = "Focus on controlled descent",
                            OrderIndex = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222224"),
                            OrderIndex = 2,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222225"),
                            Notes = "Add weight if possible",
                            OrderIndex = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateId = new Guid("33333333-3333-3333-3333-333333333332")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222226"),
                            OrderIndex = 2,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateId = new Guid("33333333-3333-3333-3333-333333333332")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Notes = "Go deep",
                            OrderIndex = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = new Guid("22222222-2222-2222-2222-222222222223"),
                            Notes = "Keep back neutral",
                            OrderIndex = 2,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkoutTemplateId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "CreatedByUser")
                        .WithMany("CustomExercises")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseRecordEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "User")
                        .WithMany("ExerciseRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.SetEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutExerciseEf", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.TemplateSetEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateExerciseEf", "WorkoutTemplateExercise")
                        .WithMany("PlannedSets")
                        .HasForeignKey("WorkoutTemplateExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplateExercise");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.UserAchievementEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.AchievementEf", "AchievementEf")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "UserEf")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchievementEf");

                    b.Navigation("UserEf");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutExerciseEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutEf", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", "User")
                        .WithMany("WorkoutTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateExerciseEf", b =>
                {
                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.ExerciseEf", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.UserEf", b =>
                {
                    b.Navigation("CustomExercises");

                    b.Navigation("ExerciseRecords");

                    b.Navigation("UserAchievements");

                    b.Navigation("WorkoutTemplates");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutEf", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutExerciseEf", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateEf", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitTracker.Infrastructure.Persistence.Data.Entities.WorkoutTemplateExerciseEf", b =>
                {
                    b.Navigation("PlannedSets");
                });
#pragma warning restore 612, 618
        }
    }
}
