<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>c42ac4a3-15c9-49d1-8b54-fec4a59f66c5</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="13.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
		<PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Mvc" Version="1.5.0" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FitTracker.Infrastructure\FitTracker.Infrastructure.csproj" />
		<ProjectReference Include="..\FitTracker.Application\FitTracker.Application.csproj" />
		<ProjectReference Include="..\FitTracker.Domain\FitTracker.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Filters\" />
		<Folder Include="Middlewares\" />
		<Folder Include="Helpers\" />
		<Folder Include="Swagger\" />
	</ItemGroup>

</Project>
