name: .NET CI with Tests and Coverage

on:
  push:
    branches:
      - 'feature/**'   # Push in feature
      - 'develop'      # Push to develop
      - 'main'         # Run tests
  pull_request:
    branches:
      - main           # Before pull run tests

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: ./backend
        run: dotnet restore

      - name: Build
        working-directory: ./backend
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test ./backend/FitTracker.Tests/FitTrackerDomain.Tests.csproj -c Release --collect:"XPlat Code Coverage"

      - name: Debug - List coverage files
        run: |
          echo "Contents of TestResults:"
          find ./backend/FitTracker.Tests/TestResults -type f -name "*.xml"
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./backend/FitTracker.Tests/TestResults/
          flags: backend
          fail_ci_if_error: true
